CONTAINER Mplanetatmosphere
{
	NAME Mplanetatmosphere;
    INCLUDE Mpreview;
	INCLUDE Mbase;
	
	GROUP Obaselist
	{
		BOOL MATERIAL_PAGE_PROPERTIES { HIDDEN; PAGE; PARENTMSG ID_MATERIALPROPERTIES; }
		BOOL MATERIAL_PAGE_LIGHT { HIDDEN; PAGE; PARENTMSG GROUP_LIGHTINCLUSION; }
	}
	
	GROUP ID_MATERIALPROPERTIES
	{
	  DEFAULT 1;
	
	REAL RADIUS_UNITS_ALTERNATIVE_NAME { HIDDEN; }
	REAL RADIUS_KM_ALTERNATIVE_NAME { HIDDEN; }
	
	LONG GEOMETRY_TYPE
	{       
		CYCLE 
		{
			ID_GEOMETRY_SPHERE;
			ID_GEOMETRY_FLAT;
			ID_GEOMETRY_CYLINDER;
		}
	}
	
	REAL RADIUS_UNITS { MIN 0; MINEX; UNIT METER; }
	REAL RADIUS_KM { MIN 0; MINEX; }
		
    REAL KM_PER_UNIT {}
    REAL UNIT_PER_KM { UNIT METER; }
    
    SEPARATOR {}
    
    REAL GLOBAL_DENSITY { MIN 0; MINEX; UNIT PERCENT; }
    REAL SCATTER_INTENSITY { UNIT PERCENT; MIN 0; MINEX; }
    
	REAL INTEGRATION_STEP_SIZE { MIN 0; MINEX; STEP 0.1; }
	REAL MAX_INTEGRATION_ERROR { MIN 0; MINEX; STEP 0.1; MAX 100.; UNIT PERCENT;  }
    REAL MAX_INTEGRATION_ERROR_FOR_GI { MIN 0; MINEX; STEP 0.1; MAX 100.; UNIT PERCENT; }
	BOOL MONTE_CARLO_HYBRID_INTEGRATION {}
	
    SEPARATOR {}
    
    GROUP GROUP_CONSTITUENT1
    {
      DEFAULT 1;
      //BOOL ID1_ON { }
      REAL ID1_DECAY_HEIGHT { MIN 0; MINEX; }
      REAL ID1_DECAY_HEIGHT_UNITS { UNIT METER; }
      REAL ID1_DENSITY { MIN 0; MINEX; UNIT PERCENT; }
      VECTOR ID1_PHASE_FACTOR { }
      //LONG ID1_PHASE_TYPE 
      //{
      //  CYCLE 
      //  {
      //    ID_PHASE_TYPE_RAYLEIGH;
      //    ID_PHASE_TYPE_MIE;
      //  }
      //}      
    }
    
    GROUP GROUP_CONSTITUENT2
    {
      DEFAULT 1;
      //BOOL ID2_ON { }
      REAL ID2_DECAY_HEIGHT { MIN 0; MINEX; }
      REAL ID2_DECAY_HEIGHT_UNITS { UNIT METER; }
      REAL ID2_DENSITY { MIN 0; MINEX; UNIT PERCENT; }
      VECTOR ID2_PHASE_FACTOR { }
      //LONG ID2_PHASE_TYPE 
      //{
      //  CYCLE 
      //  {
      //    ID_PHASE_TYPE_RAYLEIGH;
      //    ID_PHASE_TYPE_MIE;
      //  }
      //}
      VECTOR ID2_ABSORPTION_FACTOR { MIN 0; }
    }
	}

	GROUP GROUP_LIGHTINCLUSION
	{ 
	  IN_EXCLUDE LIGHTINCLUSION
	  {
	    OPEN;
	    ACCEPT { Olight; }
	  }
	}
	
	INCLUDE Millum;
	INCLUDE Massign;	
}