#ifndef _Mplanetatmosphere_H_
#define _Mplanetatmosphere_H_

enum
{
  RADIUS_UNITS = 1000,
  RADIUS_KM,
  KM_PER_UNIT,
  UNIT_PER_KM,
  _REMOVED4_, //CENTER_UNITS,
  GLOBAL_DENSITY,  
  SCATTER_INTENSITY,
  _REMOVED1_,
  NUM_INTEGRATION_STEPS,
  _REMOVED2_,
  LIGHTINCLUSION,
  GROUP_LIGHTINCLUSION,
  MATERIAL_PAGE_LIGHT,
  _REMOVED3_,
  INTEGRATION_STEP_SIZE,
  //MAX_SUBSTEP_LEVELS,
  MAX_INTEGRATION_ERROR,
  MAX_INTEGRATION_ERROR_FOR_GI,
  GEOMETRY_TYPE,
  RADIUS_UNITS_ALTERNATIVE_NAME,
  RADIUS_KM_ALTERNATIVE_NAME,
  MONTE_CARLO_HYBRID_INTEGRATION,
  
  ID_GEOMETRY_SPHERE = 0,
  ID_GEOMETRY_FLAT = 1,
  ID_GEOMETRY_CYLINDER = 2,

  ID_PHASE_TYPE_RAYLEIGH = 0,
  ID_PHASE_TYPE_MIE = 1,

  ID_ON = 1,
  ID_DECAY_HEIGHT,
  ID_DECAY_HEIGHT_UNITS,
  ID_DENSITY,
  ID_PHASE_FACTOR,
  ID_PHASE_TYPE,
  ID_ABSORPTION_FACTOR,
  
  NUM_CONSTITUENTS = 2,
  
  GROUP_CONSTITUENT1 = 2000,
  ID1_ON,
  ID1_DECAY_HEIGHT,
  ID1_DECAY_HEIGHT_UNITS,
  ID1_DENSITY,
  ID1_PHASE_FACTOR,
  ID1_PHASE_TYPE,

  GROUP_CONSTITUENT2 = 3000,
  ID2_ON,
  ID2_DECAY_HEIGHT,
  ID2_DECAY_HEIGHT_UNITS,
  ID2_DENSITY,
  ID2_PHASE_FACTOR,
  ID2_PHASE_TYPE,
  ID2_ABSORPTION_FACTOR,
  
  DEBUG_ELEMENTS = 4000,

  DUMMY,
};

#endif