#pragma once

enum
{
	IDS_PARTICLEVOLUME,		
	
  IDS_CONSTIT_DECAY_HEIGHT,
  IDS_CONSTIT_DENSITY,
  IDS_CONSTIT_PHASE_FACTOR,
  IDS_CONSTIT_PHASE_TYPE,	
  IDS_CONSTIT_PHASE_TYPE_RAYLEIGH,
  IDS_CONSTIT_PHASE_TYPE_MIE,
	IDS_CONSTIT_DECAY_HEIGHT_UNITS,

  IDS_GROUND,
  IDS_GROUND2,
  IDS_LOW,
  IDS_HIGH,
  
  IDS_LIGHT_POINT,
  IDS_LIGHT_DIRECTIONAL,

// End of symbol definition
  _DUMMY_ELEMENT_
};
